[tool.poetry]
name = "dojo"
version = "0.1.0"
description = ""
authors = ["mitch <benq7879@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
